<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.7.1</Version>
    <Authors>Dan Sonntag</Authors>
    <Company />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="5.0.0-nightly-02605" />
    <PackageReference Include="DSharpPlus.Commands" Version="5.0.0-nightly-02605" />
    <PackageReference Include="DSharpPlus.Voice" Version="5.0.0-nightly-02605" />
    <PackageReference Include="NAudio" Version="3.1.0" />
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>

</Project>
